import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        // Primary Indigo
        primary: {
          DEFAULT: "var(--color-primary)",
          light: "var(--color-primary-light)",
          lighter: "var(--color-primary-lighter)",
          soft: "var(--color-primary-soft)",
          subtle: "var(--color-primary-subtle)",
          wash: "var(--color-primary-wash)",
          hover: "var(--color-primary-hover)",
          active: "var(--color-primary-active)",
          deep: "var(--color-primary-deep)",
          dark: "var(--color-primary-dark)",
          abyss: "var(--color-primary-abyss)",
          foreground: "var(--color-on-primary)",
        },
        // Accent Gold
        accent: {
          DEFAULT: "var(--color-accent)",
          light: "var(--color-accent-light)",
          lighter: "var(--color-accent-lighter)",
          soft: "var(--color-accent-soft)",
          subtle: "var(--color-accent-subtle)",
          wash: "var(--color-accent-wash)",
          hover: "var(--color-accent-hover)",
          active: "var(--color-accent-active)",
          foreground: "var(--color-on-accent)",
        },
        // Neutral Ink
        ink: {
          DEFAULT: "var(--color-ink)",
          strong: "var(--color-ink-strong)",
          muted: "var(--color-ink-muted)",
          soft: "var(--color-ink-soft)",
          faint: "var(--color-ink-faint)",
        },
        // Dark Surfaces
        surface: {
          dark: "var(--color-surface-dark)",
          "dark-elevated": "var(--color-surface-dark-elevated)",
          "dark-raised": "var(--color-surface-dark-raised)",
        },
        on: {
          dark: "var(--color-on-dark)",
          "dark-soft": "var(--color-on-dark-soft)",
          "dark-muted": "var(--color-on-dark-muted)",
        },
        // Semantic
        success: {
          DEFAULT: "var(--color-success)",
          soft: "var(--color-success-soft)",
          "on-soft": "var(--color-success-on-soft)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          soft: "var(--color-warning-soft)",
          "on-soft": "var(--color-warning-on-soft)",
        },
        error: {
          DEFAULT: "var(--color-error)",
          soft: "var(--color-error-soft)",
          "on-soft": "var(--color-error-on-soft)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          soft: "var(--color-info-soft)",
          "on-soft": "var(--color-info-on-soft)",
        },
        // Platform Brand Colors
        platform: {
          twitter: "var(--color-platform-twitter)",
          instagram: "var(--color-platform-instagram)",
          facebook: "var(--color-platform-facebook)",
          youtube: "var(--color-platform-youtube)",
          linkedin: "var(--color-platform-linkedin)",
          threads: "var(--color-platform-threads)",
          tiktok: "var(--color-platform-tiktok)",
          "tiktok-accent": "var(--color-platform-tiktok-accent)",
          pinterest: "var(--color-platform-pinterest)",
          reddit: "var(--color-platform-reddit)",
          bluesky: "var(--color-platform-bluesky)",
          telegram: "var(--color-platform-telegram)",
          discord: "var(--color-platform-discord)",
          snapchat: "var(--color-platform-snapchat)",
          googlebusiness: "var(--color-platform-googlebusiness)",
          whatsapp: "var(--color-platform-whatsapp)",
        },
        // Utility token aliases
        hairline: "var(--color-hairline)",
        "hairline-soft": "var(--color-hairline-soft)",
        canvas: "var(--color-canvas)",
        "canvas-pure": "var(--color-canvas-pure)",
      },
      fontFamily: {
        display: ["var(--font-plus-jakarta)", "sans-serif"],
        body: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-1px", fontWeight: "700" }],
        "display-lg": ["36px", { lineHeight: "1.15", letterSpacing: "-0.5px", fontWeight: "700" }],
        "display-md": ["30px", { lineHeight: "1.2", letterSpacing: "-0.25px", fontWeight: "600" }],
        "display-sm": ["24px", { lineHeight: "1.25", fontWeight: "600" }],
        "heading-lg": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "heading-md": ["18px", { lineHeight: "1.35", fontWeight: "600" }],
        "heading-sm": ["16px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.55" }],
        "body-md": ["16px", { lineHeight: "1.5" }],
        "body-sm": ["14px", { lineHeight: "1.5" }],
        caption: ["13px", { lineHeight: "1.45" }],
        "caption-uppercase": ["12px", { lineHeight: "1.4", letterSpacing: "1px", fontWeight: "500" }],
        micro: ["11px", { lineHeight: "1.4", fontWeight: "500" }],
        code: ["14px", { lineHeight: "1.6" }],
        "code-sm": ["12px", { lineHeight: "1.5" }],
        button: ["14px", { lineHeight: "1", fontWeight: "600" }],
        "button-sm": ["13px", { lineHeight: "1", fontWeight: "600" }],
        "button-lg": ["16px", { lineHeight: "1", fontWeight: "600" }],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        pill: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "20px",
        xl: "24px",
        xxl: "32px",
        "3xl": "40px",
        "4xl": "48px",
        "5xl": "64px",
        section: "80px",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        glow: "var(--shadow-glow)",
        "glow-accent": "var(--shadow-glow-accent)",
        "dark-xs": "var(--shadow-dark-xs)",
        "dark-sm": "var(--shadow-dark-sm)",
        "dark-md": "var(--shadow-dark-md)",
        "dark-lg": "var(--shadow-dark-lg)",
        "dark-xl": "var(--shadow-dark-xl)",
      },
      transitionDuration: {
        fast: "150ms",
        normal: "250ms",
        slow: "350ms",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
};
export default config;
